package com.yellowyotu.hbmneoforge;

import com.yellowyotu.hbmneoforge.item.ItemBatteryPack;

import com.yellowyotu.hbmneoforge.item.*;
import com.yellowyotu.hbmneoforge.radiation.RadiationValues;
import net.minecraft.world.item.ArmorItem;
import net.minecraft.world.item.BlockItem;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.DoubleHighBlockItem;
import net.neoforged.bus.api.IEventBus;
import net.neoforged.neoforge.registries.DeferredItem;
import net.neoforged.neoforge.registries.DeferredRegister;

public final class ModItems {
    public static final DeferredRegister.Items ITEMS = DeferredRegister.createItems(HBMsNuclearTechModUnofficialNeoForgeEdition.MODID);

    public static final DeferredItem<Item> INGOT_STEEL = simple("ingot_steel");
    public static final DeferredItem<Item> PLATE_STEEL = simple("plate_steel");
    public static final DeferredItem<Item> PLATE_COPPER = simple("plate_copper");
    public static final DeferredItem<Item> PLATE_IRON = simple("plate_iron");
    public static final DeferredItem<Item> INGOT_TITANIUM = simple("ingot_titanium");
    public static final DeferredItem<Item> PLATE_TITANIUM = simple("plate_titanium");
    public static final DeferredItem<ItemShredderBlade> BLADES_STEEL = ITEMS.register("blades_steel", () -> new ItemShredderBlade(new Item.Properties().durability(400).stacksTo(1)));
    public static final DeferredItem<ItemShredderBlade> BLADES_TITANIUM = ITEMS.register("blades_titanium", () -> new ItemShredderBlade(new Item.Properties().durability(500).stacksTo(1)));
    public static final DeferredItem<Item> SCRAP = simple("scrap");
    public static final DeferredItem<Item> DUST = simple("dust");
    public static final DeferredItem<Item> POWDER_IRON = simple("powder_iron");
    public static final DeferredItem<Item> POWDER_STEEL = simple("powder_steel");
    public static final DeferredItem<Item> POWDER_COPPER = simple("powder_copper");
    public static final DeferredItem<Item> POWDER_TITANIUM = simple("powder_titanium");
    public static final DeferredItem<Item> POWDER_TUNGSTEN = simple("powder_tungsten");
    public static final DeferredItem<Item> POWDER_ALUMINIUM = simple("powder_aluminium");
    public static final DeferredItem<Item> POWDER_BERYLLIUM = simple("powder_beryllium");
    public static final DeferredItem<Item> POWDER_LEAD = simple("powder_lead");
    public static final DeferredItem<Item> POWDER_COBALT = simple("powder_cobalt");
    public static final DeferredItem<Item> POWDER_BORON = simple("powder_boron");
    public static final DeferredItem<Item> POWDER_URANIUM = simple("powder_uranium");
    public static final DeferredItem<Item> POWDER_PLUTONIUM = simple("powder_plutonium");
    public static final DeferredItem<Item> POWDER_RED_COPPER = simple("powder_red_copper");
    public static final DeferredItem<Item> POWDER_DURA_STEEL = simple("powder_dura_steel");
    public static final DeferredItem<Item> POWDER_GUNMETAL = simple("powder_gunmetal");
    public static final DeferredItem<Item> POWDER_COAL = simple("powder_coal");
    public static final DeferredItem<Item> POWDER_GOLD = simple("powder_gold");
    public static final DeferredItem<Item> POWDER_POLYMER = simple("powder_polymer");
    public static final DeferredItem<Item> POWDER_BAKELITE = simple("powder_bakelite");
    public static final DeferredItem<Item> POWDER_QUARTZ = simple("powder_quartz");
    public static final DeferredItem<Item> POWDER_ICE = simple("powder_ice");
    public static final DeferredItem<Item> POWDER_SAWDUST = simple("powder_sawdust");
    public static final DeferredItem<Item> POWDER_DESH_MIX = simple("powder_desh_mix");
    public static final DeferredItem<Item> POWDER_COBALT_TINY = simple("powder_cobalt_tiny");
    public static final DeferredItem<Item> BIOMASS = simple("biomass");
    public static final DeferredItem<ItemMaterialTooltip> INGOT_TUNGSTEN = ITEMS.register("ingot_tungsten", () -> new ItemMaterialTooltip(new Item.Properties(), ItemMaterialTooltip.TooltipType.TUNGSTEN));

    public static final DeferredItem<RadioactiveItem> INGOT_URANIUM = radioactive("ingot_uranium", RadiationValues.URANIUM_INGOT);
    public static final DeferredItem<Item> INGOT_ALUMINIUM = simple("ingot_aluminium");
    public static final DeferredItem<Item> PLATE_ALUMINIUM = simple("plate_aluminium");
    public static final DeferredItem<Item> INGOT_BERYLLIUM = simple("ingot_beryllium");
    public static final DeferredItem<Item> INGOT_LEAD = simple("ingot_lead");
    public static final DeferredItem<Item> PLATE_LEAD = simple("plate_lead");
    public static final DeferredItem<Item> INGOT_COPPER = simple("ingot_copper");
    public static final DeferredItem<Item> INGOT_BORON = simple("ingot_boron");
    public static final DeferredItem<Item> INGOT_GRAPHITE = simple("ingot_graphite");
    public static final DeferredItem<Item> INGOT_COBALT = simple("ingot_cobalt");
    public static final DeferredItem<Item> BILLET_COBALT = simple("billet_cobalt");
    public static final DeferredItem<Item> FRAGMENT_COBALT = simple("fragment_cobalt");
    public static final DeferredItem<Item> NUGGET_COBALT = simple("nugget_cobalt");
    public static final DeferredItem<Item> RARE_EARTH_ORE_CHUNK = simple("rare_earth_ore_chunk");
    public static final DeferredItem<RadioactiveItem> INGOT_U233 = radioactive("ingot_u233", RadiationValues.URANIUM_233_INGOT);
    public static final DeferredItem<RadioactiveItem> INGOT_U235 = radioactive("ingot_u235", RadiationValues.URANIUM_235_INGOT);
    public static final DeferredItem<RadioactiveItem> INGOT_U238 = radioactive("ingot_u238", RadiationValues.URANIUM_238_INGOT);
    public static final DeferredItem<RadioactiveItem> INGOT_PLUTONIUM = radioactive("ingot_plutonium", RadiationValues.PLUTONIUM_INGOT);
    public static final DeferredItem<RadioactiveItem> GADGET_CORE = radioactive("gadget_core", RadiationValues.GADGET_CORE);
    public static final DeferredItem<RadioactiveItem> FALLOUT = radioactive("fallout", RadiationValues.FALLOUT_ITEM);

    public static final DeferredItem<Item> WIRE_ALUMINIUM = simple("wire_aluminium");
    public static final DeferredItem<Item> WIRE_COPPER = simple("wire_copper");
    public static final DeferredItem<Item> WIRE_TUNGSTEN = simple("wire_tungsten");
    public static final DeferredItem<Item> WIRE_CARBON = simple("wire_carbon");
    public static final DeferredItem<Item> IRON_PIPE = simple("iron_pipe");
    public static final DeferredItem<Item> WIRE_RED_COPPER = simple("wire_red_copper");
    public static final DeferredItem<Item> INGOT_RED_COPPER = simple("ingot_red_copper");
    public static final DeferredItem<Item> PLATE_POLYMER = simple("plate_polymer");
    public static final DeferredItem<Item> BALL_RESIN = simple("ball_resin");
    public static final DeferredItem<Item> INGOT_BIORUBBER = simple("ingot_biorubber");
    public static final DeferredItem<Item> INGOT_DURA_STEEL = simple("ingot_dura_steel");
    public static final DeferredItem<Item> BOLT_DURA_STEEL = simple("bolt_dura_steel");
    public static final DeferredItem<Item> MOTOR = simple("motor");
    public static final DeferredItem<Item> COPPER_COIL = simple("copper_coil");
    public static final DeferredItem<Item> RING_COIL = simple("ring_coil");
    public static final DeferredItem<Item> BOLT_STEEL = simple("bolt_steel");
    public static final DeferredItem<Item> BOLT_TUNGSTEN = simple("bolt_tungsten");
    public static final DeferredItem<Item> BOLT_LEAD = simple("bolt_lead");
    public static final DeferredItem<RadioactiveItem> INGOT_PLUTONIUM_239 = radioactive("ingot_plutonium_239", RadiationValues.PLUTONIUM_239_INGOT);
    public static final DeferredItem<RadioactiveItem> INGOT_PLUTONIUM_240 = radioactive("ingot_plutonium_240", RadiationValues.PLUTONIUM_240_INGOT);
    public static final DeferredItem<RadioactiveItem> INGOT_PLUTONIUM_241 = radioactive("ingot_plutonium_241", RadiationValues.PLUTONIUM_241_INGOT);
    public static final DeferredItem<Item> PLATE_GOLD = simple("plate_gold");
    public static final DeferredItem<Item> INGOT_GUNMETAL = simple("ingot_gunmetal");
    public static final DeferredItem<Item> SYRINGE_EMPTY = simple("syringe_empty");
    public static final DeferredItem<Item> CELL_EMPTY = simple("cell_empty");
    public static final DeferredItem<Item> CIRCUIT_VACUUM_TUBE = simple("circuit_vacuum_tube");
    public static final DeferredItem<Item> CIRCUIT_CAPACITOR = simple("circuit_capacitor");
    public static final DeferredItem<Item> CIRCUIT_CAPACITOR_TANTALIUM = simple("circuit_capacitor_tantalium");
    public static final DeferredItem<Item> CIRCUIT_PCB = simple("circuit_pcb");
    public static final DeferredItem<Item> CIRCUIT_CHIP = simple("circuit_chip");
    public static final DeferredItem<Item> CIRCUIT_CHIP_BISMOID = simple("circuit_chip_bismoid");
    public static final DeferredItem<Item> CIRCUIT_ANALOG = simple("circuit_analog");
    public static final DeferredItem<Item> CIRCUIT_BASIC = simple("circuit_basic");
    public static final DeferredItem<Item> CIRCUIT_ADVANCED = simple("circuit_advanced");
    public static final DeferredItem<Item> CIRCUIT_CAPACITOR_BOARD = simple("circuit_capacitor_board");
    public static final DeferredItem<Item> CIRCUIT_BISMOID = simple("circuit_bismoid");
    public static final DeferredItem<Item> CIRCUIT_QUANTUM = simple("circuit_quantum");
    public static final DeferredItem<Item> CIRCUIT_CHIP_QUANTUM = simple("circuit_chip_quantum");
    public static final DeferredItem<Item> CIRCUIT_ATOMIC_CLOCK = simple("circuit_atomic_clock");
    public static final DeferredItem<Item> CIRCUIT_CONTROLLER_CHASSIS = simple("circuit_controller_chassis");
    public static final DeferredItem<Item> CIRCUIT_CONTROLLER = simple("circuit_controller");
    public static final DeferredItem<Item> CIRCUIT_CONTROLLER_ADVANCED = simple("circuit_controller_advanced");
    public static final DeferredItem<Item> CIRCUIT_CONTROLLER_QUANTUM = simple("circuit_controller_quantum");
    public static final DeferredItem<Item> WIRE_FINE_LEAD = simple("wire_fine_lead");
    public static final DeferredItem<Item> UPGRADE_TEMPLATE = simple("upgrade_template");
    public static final DeferredItem<ItemMachineUpgrade> UPGRADE_SPEED_1 = upgrade("upgrade_speed_1", ItemMachineUpgrade.UpgradeType.SPEED, 1);
    public static final DeferredItem<ItemMachineUpgrade> UPGRADE_SPEED_2 = upgrade("upgrade_speed_2", ItemMachineUpgrade.UpgradeType.SPEED, 2);
    public static final DeferredItem<ItemMachineUpgrade> UPGRADE_SPEED_3 = upgrade("upgrade_speed_3", ItemMachineUpgrade.UpgradeType.SPEED, 3);
    public static final DeferredItem<ItemMachineUpgrade> UPGRADE_POWER_1 = upgrade("upgrade_power_1", ItemMachineUpgrade.UpgradeType.POWER, 1);
    public static final DeferredItem<ItemMachineUpgrade> UPGRADE_POWER_2 = upgrade("upgrade_power_2", ItemMachineUpgrade.UpgradeType.POWER, 2);
    public static final DeferredItem<ItemMachineUpgrade> UPGRADE_POWER_3 = upgrade("upgrade_power_3", ItemMachineUpgrade.UpgradeType.POWER, 3);
    public static final DeferredItem<ItemMachineUpgrade> UPGRADE_OVERDRIVE_1 = upgrade("upgrade_overdrive_1", ItemMachineUpgrade.UpgradeType.OVERDRIVE, 1);
    public static final DeferredItem<ItemMachineUpgrade> UPGRADE_OVERDRIVE_2 = upgrade("upgrade_overdrive_2", ItemMachineUpgrade.UpgradeType.OVERDRIVE, 2);
    public static final DeferredItem<ItemMachineUpgrade> UPGRADE_OVERDRIVE_3 = upgrade("upgrade_overdrive_3", ItemMachineUpgrade.UpgradeType.OVERDRIVE, 3);
    public static final DeferredItem<ItemSolderingFluidCell> CELL_SULFURIC_ACID = fluidCell("cell_sulfuric_acid", ItemSolderingFluidCell.FluidType.SULFURIC_ACID);
    public static final DeferredItem<ItemSolderingFluidCell> CELL_PEROXIDE = fluidCell("cell_peroxide", ItemSolderingFluidCell.FluidType.PEROXIDE);
    public static final DeferredItem<ItemSolderingFluidCell> CELL_SOLVENT = fluidCell("cell_solvent", ItemSolderingFluidCell.FluidType.SOLVENT);
    public static final DeferredItem<ItemSolderingFluidCell> CELL_HELIUM4 = fluidCell("cell_helium4", ItemSolderingFluidCell.FluidType.HELIUM4);
    public static final DeferredItem<ItemSolderingFluidCell> CELL_PERFLUOROMETHYL = fluidCell("cell_perfluoromethyl", ItemSolderingFluidCell.FluidType.PERFLUOROMETHYL);
    public static final DeferredItem<ItemSolderingFluidCell> CELL_PERFLUOROMETHYL_COLD = fluidCell("cell_perfluoromethyl_cold", ItemSolderingFluidCell.FluidType.PERFLUOROMETHYL_COLD);
    public static final DeferredItem<Item> IV_BAG = simple("iv_bag");
    public static final DeferredItem<ItemRadAway> RADAWAY = ITEMS.register("radaway", () -> new ItemRadAway(new Item.Properties()));
    public static final DeferredItem<ItemRadX> RAD_X = ITEMS.register("radx", () -> new ItemRadX(new Item.Properties()));
    public static final DeferredItem<Item> INGOT_RUBBER = simple("ingot_rubber");
    public static final DeferredItem<Item> INGOT_BAKELITE = simple("ingot_bakelite");
    public static final DeferredItem<Item> INGOT_POLYMER = simple("ingot_polymer");
    public static final DeferredItem<Item> HAZMAT_CLOTH = simple("hazmat_cloth");
    public static final DeferredItem<ArmorItem> HAZMAT_HELMET = ITEMS.register("hazmat_helmet", () -> new ArmorItem(ModArmorMaterials.HAZMAT, ArmorItem.Type.HELMET, new Item.Properties().durability(ArmorItem.Type.HELMET.getDurability(60))));
    public static final DeferredItem<ArmorItem> HAZMAT_PLATE = ITEMS.register("hazmat_plate", () -> new ArmorItem(ModArmorMaterials.HAZMAT, ArmorItem.Type.CHESTPLATE, new Item.Properties().durability(ArmorItem.Type.CHESTPLATE.getDurability(60))));
    public static final DeferredItem<ArmorItem> HAZMAT_LEGS = ITEMS.register("hazmat_legs", () -> new ArmorItem(ModArmorMaterials.HAZMAT, ArmorItem.Type.LEGGINGS, new Item.Properties().durability(ArmorItem.Type.LEGGINGS.getDurability(60))));
    public static final DeferredItem<ArmorItem> HAZMAT_BOOTS = ITEMS.register("hazmat_boots", () -> new ArmorItem(ModArmorMaterials.HAZMAT, ArmorItem.Type.BOOTS, new Item.Properties().durability(ArmorItem.Type.BOOTS.getDurability(60))));
    public static final DeferredItem<Item> ASSEMBLY_PART_RING = simple("assembly_part_ring");
    public static final DeferredItem<Item> ASSEMBLY_PART_ARM_LOWER_1 = simple("assembly_part_arm_lower_1");
    public static final DeferredItem<Item> ASSEMBLY_PART_ARM_UPPER_1 = simple("assembly_part_arm_upper_1");
    public static final DeferredItem<Item> ASSEMBLY_PART_HEAD_1 = simple("assembly_part_head_1");
    public static final DeferredItem<Item> ASSEMBLY_PART_SPIKE_1 = simple("assembly_part_spike_1");
    public static final DeferredItem<Item> ASSEMBLY_PART_ARM_LOWER_2 = simple("assembly_part_arm_lower_2");
    public static final DeferredItem<Item> ASSEMBLY_PART_ARM_UPPER_2 = simple("assembly_part_arm_upper_2");
    public static final DeferredItem<Item> ASSEMBLY_PART_HEAD_2 = simple("assembly_part_head_2");
    public static final DeferredItem<Item> ASSEMBLY_PART_SPIKE_2 = simple("assembly_part_spike_2");

    public static final DeferredItem<ItemStamp> STAMP_IRON_FLAT = stamp("stamp_iron_flat", 64, ItemStamp.StampType.FLAT);
    public static final DeferredItem<ItemStamp> IRON_PLATE_STAMP = stamp("iron_plate_stamp", 64, ItemStamp.StampType.PLATE);
    public static final DeferredItem<ItemStamp> STAMP_IRON_WIRE = stamp("stamp_iron_wire", 64, ItemStamp.StampType.WIRE);
    public static final DeferredItem<ItemStamp> STAMP_IRON_CIRCUIT = stamp("stamp_iron_circuit", 64, ItemStamp.StampType.CIRCUIT);
    public static final DeferredItem<ItemStamp> STAMP_STEEL_FLAT = stamp("stamp_steel_flat", 192, ItemStamp.StampType.FLAT);
    public static final DeferredItem<ItemStamp> STAMP_STEEL_PLATE = stamp("stamp_steel_plate", 192, ItemStamp.StampType.PLATE);
    public static final DeferredItem<ItemStamp> STAMP_STEEL_WIRE = stamp("stamp_steel_wire", 192, ItemStamp.StampType.WIRE);
    public static final DeferredItem<ItemStamp> STAMP_STEEL_CIRCUIT = stamp("stamp_steel_circuit", 192, ItemStamp.StampType.CIRCUIT);

    public static final DeferredItem<Item> CAP_NUKA = ITEMS.registerSimpleItem("cap_nuka", new Item.Properties().stacksTo(64));
    public static final DeferredItem<Item> BOTTLE_EMPTY = ITEMS.registerSimpleItem("bottle_empty", new Item.Properties().stacksTo(64));
    public static final DeferredItem<ItemNukaCola> BOTTLE_NUKA = ITEMS.register("bottle_nuka", () -> new ItemNukaCola(new Item.Properties().stacksTo(16)));
    public static final DeferredItem<ItemCigarette> CIGARETTE = ITEMS.register("cigarette", () -> new ItemCigarette(new Item.Properties().stacksTo(16)));
    public static final DeferredItem<RadioactiveItem> PELLET_RTG = ITEMS.register("pellet_rtg", () -> new RadioactiveItem(new Item.Properties().stacksTo(1), RadiationValues.PELLET_RTG));
    public static final DeferredItem<ItemGeigerCounter> GEIGER_COUNTER = ITEMS.register("geiger_counter", () -> new ItemGeigerCounter(new Item.Properties().stacksTo(1)));
    public static final DeferredItem<ItemBatteryPack> BATTERY_PACK = ITEMS.register("battery_pack", () -> new ItemBatteryPack(new Item.Properties().stacksTo(1)));


    public static final DeferredItem<BlockItem> CAGE_LAMP = ITEMS.register("spotlight_incandescent", () -> new BlockItem(ModBlocks.CAGE_LAMP.get(), new Item.Properties()));
    public static final DeferredItem<BlockItem> REINFORCED_GLASS = ITEMS.register("reinforced_glass", () -> new BlockItem(ModBlocks.REINFORCED_GLASS.get(), new Item.Properties()));
    public static final DeferredItem<BlockItem> REINFORCED_GLASS_PANE = ITEMS.register("reinforced_glass_pane", () -> new BlockItem(ModBlocks.REINFORCED_GLASS_PANE.get(), new Item.Properties()));
    public static final DeferredItem<BlockItem> CONCRETE_COLORED_EXT_HAZARD = ITEMS.register("concrete_colored_ext_hazard", () -> new BlockItem(ModBlocks.CONCRETE_COLORED_EXT_HAZARD.get(), new Item.Properties()));

    public static final DeferredItem<BlockItem> SLIDING_SEAL_DOOR = ITEMS.register("sliding_seal_door", () -> new BlockItem(ModBlocks.SLIDING_SEAL_DOOR.get(), new Item.Properties()));
    public static final DeferredItem<BlockItem> ASSEMBLY_MACHINE = ITEMS.register("assembly_machine", () -> new BlockItem(ModBlocks.ASSEMBLY_MACHINE.get(), new Item.Properties()));
    public static final DeferredItem<BlockItem> MACHINE_BATTERY_SOCKET = ITEMS.register("machine_battery_socket", () -> new BlockItem(ModBlocks.MACHINE_BATTERY_SOCKET.get(), new Item.Properties()));
    public static final DeferredItem<BlockItem> BLOCK_RED_COPPER = ITEMS.register("block_red_copper", () -> new BlockItem(ModBlocks.BLOCK_RED_COPPER.get(), new Item.Properties()));
    public static final DeferredItem<BlockItem> RED_CABLE = ITEMS.register("red_cable", () -> new BlockItem(ModBlocks.RED_CABLE.get(), new Item.Properties()));
    public static final DeferredItem<BlockItem> SHREDDER = ITEMS.register("machine_shredder", () -> new BlockItem(ModBlocks.SHREDDER.get(), new Item.Properties()));
    public static final DeferredItem<BlockItem> SOLDERING_STATION = ITEMS.register("machine_soldering_station", () -> new BlockItem(ModBlocks.SOLDERING_STATION.get(), new Item.Properties()));
    public static final DeferredItem<BlockItem> GRAVEL_OBSIDIAN = ITEMS.register("gravel_obsidian", () -> new BlockItem(ModBlocks.GRAVEL_OBSIDIAN.get(), new Item.Properties()));
    public static final DeferredItem<BlockItem> MACHINE_PRESS = ITEMS.register("machine_press", () -> new BlockItem(ModBlocks.MACHINE_PRESS.get(), new Item.Properties()));
    public static final DeferredItem<BlockItem> ORE_URANIUM = ITEMS.register("ore_uranium", () -> new BlockItem(ModBlocks.ORE_URANIUM.get(), new Item.Properties()));
    public static final DeferredItem<BlockItem> ORE_TITANIUM = ITEMS.register("ore_titanium", () -> new BlockItem(ModBlocks.ORE_TITANIUM.get(), new Item.Properties()));
    public static final DeferredItem<BlockItem> ORE_TUNGSTEN = ITEMS.register("ore_tungsten", () -> new BlockItem(ModBlocks.ORE_TUNGSTEN.get(), new Item.Properties()));
    public static final DeferredItem<BlockItem> ORE_ALUMINIUM = ITEMS.register("ore_aluminium", () -> new BlockItem(ModBlocks.ORE_ALUMINIUM.get(), new Item.Properties()));
    public static final DeferredItem<BlockItem> ORE_BERYLLIUM = ITEMS.register("ore_beryllium", () -> new BlockItem(ModBlocks.ORE_BERYLLIUM.get(), new Item.Properties()));
    public static final DeferredItem<BlockItem> ORE_LEAD = ITEMS.register("ore_lead", () -> new BlockItem(ModBlocks.ORE_LEAD.get(), new Item.Properties()));
    public static final DeferredItem<BlockItem> ORE_COBALT = ITEMS.register("ore_cobalt", () -> new BlockItem(ModBlocks.ORE_COBALT.get(), new Item.Properties()));
    public static final DeferredItem<BlockItem> ORE_RARE_EARTH = ITEMS.register("ore_rare_earth", () -> new BlockItem(ModBlocks.ORE_RARE_EARTH.get(), new Item.Properties()));
    public static final DeferredItem<BlockItem> BLOCK_COBALT = ITEMS.register("block_cobalt", () -> new BlockItem(ModBlocks.BLOCK_COBALT.get(), new Item.Properties()));
    public static final DeferredItem<BlockItem> BLOCK_LEAD = ITEMS.register("block_lead", () -> new BlockItem(ModBlocks.BLOCK_LEAD.get(), new Item.Properties()));
    public static final DeferredItem<BlockItem> BLOCK_BORON = ITEMS.register("block_boron", () -> new BlockItem(ModBlocks.BLOCK_BORON.get(), new Item.Properties()));
    public static final DeferredItem<BlockItem> PWR_CONTROLLER = ITEMS.register("pwr_controller", () -> new BlockItem(ModBlocks.PWR_CONTROLLER.get(), new Item.Properties()));
    public static final DeferredItem<RadioactiveBlockItem> YELLOW_BARREL = ITEMS.register("yellow_barrel", () -> new RadioactiveBlockItem(ModBlocks.YELLOW_BARREL.get(), new Item.Properties(), RadiationValues.YELLOW_BARREL_ITEM));
    public static final DeferredItem<RadioactiveBlockItem> BLOCK_FALLOUT = ITEMS.register("block_fallout", () -> new RadioactiveBlockItem(ModBlocks.BLOCK_FALLOUT.get(), new Item.Properties(), RadiationValues.FALLOUT_BLOCK_ITEM));
    public static final DeferredItem<BlockItem> RAD_ABSORBER = ITEMS.register("rad_absorber", () -> new BlockItem(ModBlocks.RAD_ABSORBER.get(), new Item.Properties()));
    public static final DeferredItem<BlockItem> WASTE_EARTH = ITEMS.register("waste_earth", () -> new BlockItem(ModBlocks.WASTE_EARTH.get(), new Item.Properties()));
    public static final DeferredItem<BlockItem> WASTE_LEAVES = ITEMS.register("waste_leaves", () -> new BlockItem(ModBlocks.WASTE_LEAVES.get(), new Item.Properties()));
    public static final DeferredItem<BlockItem> LEAVES_LAYER = ITEMS.register("leaves_layer", () -> new BlockItem(ModBlocks.LEAVES_LAYER.get(), new Item.Properties()));
    public static final DeferredItem<BlockItem> GEIGER = ITEMS.register("geiger", () -> new BlockItem(ModBlocks.GEIGER.get(), new Item.Properties()));
    public static final DeferredItem<BlockItem> ANVIL_IRON = ITEMS.register("anvil_iron", () -> new BlockItem(ModBlocks.ANVIL_IRON.get(), new Item.Properties()));
    public static final DeferredItem<BlockItem> CONCRETE = ITEMS.register("concrete", () -> new BlockItem(ModBlocks.CONCRETE.get(), new Item.Properties()));
    public static final DeferredItem<BlockItem> CONCRETE_WHITE = ITEMS.register("concrete_white", () -> new BlockItem(ModBlocks.CONCRETE_WHITE.get(), new Item.Properties()));
    public static final DeferredItem<BlockItem> CONCRETE_ORANGE = ITEMS.register("concrete_orange", () -> new BlockItem(ModBlocks.CONCRETE_ORANGE.get(), new Item.Properties()));
    public static final DeferredItem<BlockItem> CONCRETE_MAGENTA = ITEMS.register("concrete_magenta", () -> new BlockItem(ModBlocks.CONCRETE_MAGENTA.get(), new Item.Properties()));
    public static final DeferredItem<BlockItem> CONCRETE_LIGHT_BLUE = ITEMS.register("concrete_light_blue", () -> new BlockItem(ModBlocks.CONCRETE_LIGHT_BLUE.get(), new Item.Properties()));
    public static final DeferredItem<BlockItem> CONCRETE_YELLOW = ITEMS.register("concrete_yellow", () -> new BlockItem(ModBlocks.CONCRETE_YELLOW.get(), new Item.Properties()));
    public static final DeferredItem<BlockItem> CONCRETE_LIME = ITEMS.register("concrete_lime", () -> new BlockItem(ModBlocks.CONCRETE_LIME.get(), new Item.Properties()));
    public static final DeferredItem<BlockItem> CONCRETE_PINK = ITEMS.register("concrete_pink", () -> new BlockItem(ModBlocks.CONCRETE_PINK.get(), new Item.Properties()));
    public static final DeferredItem<BlockItem> CONCRETE_GRAY = ITEMS.register("concrete_gray", () -> new BlockItem(ModBlocks.CONCRETE_GRAY.get(), new Item.Properties()));
    public static final DeferredItem<BlockItem> CONCRETE_SILVER = ITEMS.register("concrete_silver", () -> new BlockItem(ModBlocks.CONCRETE_SILVER.get(), new Item.Properties()));
    public static final DeferredItem<BlockItem> CONCRETE_CYAN = ITEMS.register("concrete_cyan", () -> new BlockItem(ModBlocks.CONCRETE_CYAN.get(), new Item.Properties()));
    public static final DeferredItem<BlockItem> CONCRETE_PURPLE = ITEMS.register("concrete_purple", () -> new BlockItem(ModBlocks.CONCRETE_PURPLE.get(), new Item.Properties()));
    public static final DeferredItem<BlockItem> CONCRETE_BLUE = ITEMS.register("concrete_blue", () -> new BlockItem(ModBlocks.CONCRETE_BLUE.get(), new Item.Properties()));
    public static final DeferredItem<BlockItem> CONCRETE_BROWN = ITEMS.register("concrete_brown", () -> new BlockItem(ModBlocks.CONCRETE_BROWN.get(), new Item.Properties()));
    public static final DeferredItem<BlockItem> CONCRETE_GREEN = ITEMS.register("concrete_green", () -> new BlockItem(ModBlocks.CONCRETE_GREEN.get(), new Item.Properties()));
    public static final DeferredItem<BlockItem> CONCRETE_RED = ITEMS.register("concrete_red", () -> new BlockItem(ModBlocks.CONCRETE_RED.get(), new Item.Properties()));
    public static final DeferredItem<BlockItem> CONCRETE_BLACK = ITEMS.register("concrete_black", () -> new BlockItem(ModBlocks.CONCRETE_BLACK.get(), new Item.Properties()));
    public static final DeferredItem<BlockItem> CONCRETE_REBAR = ITEMS.register("concrete_rebar", () -> new BlockItem(ModBlocks.CONCRETE_REBAR.get(), new Item.Properties()));
    public static final DeferredItem<BlockItem> CONCRETE_ASBESTOS = ITEMS.register("concrete_asbestos", () -> new BlockItem(ModBlocks.CONCRETE_ASBESTOS.get(), new Item.Properties()));
    public static final DeferredItem<BlockItem> CONCRETE_SUPER = ITEMS.register("concrete_super", () -> new BlockItem(ModBlocks.CONCRETE_SUPER.get(), new Item.Properties()));
    public static final DeferredItem<BlockItem> CONCRETE_TILE = ITEMS.register("concrete_tile", () -> new BlockItem(ModBlocks.CONCRETE_TILE.get(), new Item.Properties()));
    public static final DeferredItem<BlockItem> BRICK_CONCRETE = ITEMS.register("brick_concrete", () -> new BlockItem(ModBlocks.BRICK_CONCRETE.get(), new Item.Properties()));
    public static final DeferredItem<BlockItem> BRICK_CONCRETE_CRACKED = ITEMS.register("brick_concrete_cracked", () -> new BlockItem(ModBlocks.BRICK_CONCRETE_CRACKED.get(), new Item.Properties()));
    public static final DeferredItem<BlockItem> BRICK_CONCRETE_MOSSY = ITEMS.register("brick_concrete_mossy", () -> new BlockItem(ModBlocks.BRICK_CONCRETE_MOSSY.get(), new Item.Properties()));
    public static final DeferredItem<BlockItem> BRICK_CONCRETE_BROKEN = ITEMS.register("brick_concrete_broken", () -> new BlockItem(ModBlocks.BRICK_CONCRETE_BROKEN.get(), new Item.Properties()));
    public static final DeferredItem<BlockItem> BRICK_CONCRETE_MARKED = ITEMS.register("brick_concrete_marked", () -> new BlockItem(ModBlocks.BRICK_CONCRETE_MARKED.get(), new Item.Properties()));

    public static final DeferredItem<BlockItem> CONCRETE_STAIRS = ITEMS.register("concrete_stairs", () -> new BlockItem(ModBlocks.CONCRETE_STAIRS.get(), new Item.Properties()));
    public static final DeferredItem<BlockItem> CONCRETE_SLAB = ITEMS.register("concrete_slab", () -> new BlockItem(ModBlocks.CONCRETE_SLAB.get(), new Item.Properties()));
    public static final DeferredItem<BlockItem> CONCRETE_WHITE_STAIRS = ITEMS.register("concrete_white_stairs", () -> new BlockItem(ModBlocks.CONCRETE_WHITE_STAIRS.get(), new Item.Properties()));
    public static final DeferredItem<BlockItem> CONCRETE_WHITE_SLAB = ITEMS.register("concrete_white_slab", () -> new BlockItem(ModBlocks.CONCRETE_WHITE_SLAB.get(), new Item.Properties()));
    public static final DeferredItem<BlockItem> CONCRETE_ORANGE_STAIRS = ITEMS.register("concrete_orange_stairs", () -> new BlockItem(ModBlocks.CONCRETE_ORANGE_STAIRS.get(), new Item.Properties()));
    public static final DeferredItem<BlockItem> CONCRETE_ORANGE_SLAB = ITEMS.register("concrete_orange_slab", () -> new BlockItem(ModBlocks.CONCRETE_ORANGE_SLAB.get(), new Item.Properties()));
    public static final DeferredItem<BlockItem> CONCRETE_MAGENTA_STAIRS = ITEMS.register("concrete_magenta_stairs", () -> new BlockItem(ModBlocks.CONCRETE_MAGENTA_STAIRS.get(), new Item.Properties()));
    public static final DeferredItem<BlockItem> CONCRETE_MAGENTA_SLAB = ITEMS.register("concrete_magenta_slab", () -> new BlockItem(ModBlocks.CONCRETE_MAGENTA_SLAB.get(), new Item.Properties()));
    public static final DeferredItem<BlockItem> CONCRETE_LIGHT_BLUE_STAIRS = ITEMS.register("concrete_light_blue_stairs", () -> new BlockItem(ModBlocks.CONCRETE_LIGHT_BLUE_STAIRS.get(), new Item.Properties()));
    public static final DeferredItem<BlockItem> CONCRETE_LIGHT_BLUE_SLAB = ITEMS.register("concrete_light_blue_slab", () -> new BlockItem(ModBlocks.CONCRETE_LIGHT_BLUE_SLAB.get(), new Item.Properties()));
    public static final DeferredItem<BlockItem> CONCRETE_YELLOW_STAIRS = ITEMS.register("concrete_yellow_stairs", () -> new BlockItem(ModBlocks.CONCRETE_YELLOW_STAIRS.get(), new Item.Properties()));
    public static final DeferredItem<BlockItem> CONCRETE_YELLOW_SLAB = ITEMS.register("concrete_yellow_slab", () -> new BlockItem(ModBlocks.CONCRETE_YELLOW_SLAB.get(), new Item.Properties()));
    public static final DeferredItem<BlockItem> CONCRETE_LIME_STAIRS = ITEMS.register("concrete_lime_stairs", () -> new BlockItem(ModBlocks.CONCRETE_LIME_STAIRS.get(), new Item.Properties()));
    public static final DeferredItem<BlockItem> CONCRETE_LIME_SLAB = ITEMS.register("concrete_lime_slab", () -> new BlockItem(ModBlocks.CONCRETE_LIME_SLAB.get(), new Item.Properties()));
    public static final DeferredItem<BlockItem> CONCRETE_PINK_STAIRS = ITEMS.register("concrete_pink_stairs", () -> new BlockItem(ModBlocks.CONCRETE_PINK_STAIRS.get(), new Item.Properties()));
    public static final DeferredItem<BlockItem> CONCRETE_PINK_SLAB = ITEMS.register("concrete_pink_slab", () -> new BlockItem(ModBlocks.CONCRETE_PINK_SLAB.get(), new Item.Properties()));
    public static final DeferredItem<BlockItem> CONCRETE_GRAY_STAIRS = ITEMS.register("concrete_gray_stairs", () -> new BlockItem(ModBlocks.CONCRETE_GRAY_STAIRS.get(), new Item.Properties()));
    public static final DeferredItem<BlockItem> CONCRETE_GRAY_SLAB = ITEMS.register("concrete_gray_slab", () -> new BlockItem(ModBlocks.CONCRETE_GRAY_SLAB.get(), new Item.Properties()));
    public static final DeferredItem<BlockItem> CONCRETE_SILVER_STAIRS = ITEMS.register("concrete_silver_stairs", () -> new BlockItem(ModBlocks.CONCRETE_SILVER_STAIRS.get(), new Item.Properties()));
    public static final DeferredItem<BlockItem> CONCRETE_SILVER_SLAB = ITEMS.register("concrete_silver_slab", () -> new BlockItem(ModBlocks.CONCRETE_SILVER_SLAB.get(), new Item.Properties()));
    public static final DeferredItem<BlockItem> CONCRETE_CYAN_STAIRS = ITEMS.register("concrete_cyan_stairs", () -> new BlockItem(ModBlocks.CONCRETE_CYAN_STAIRS.get(), new Item.Properties()));
    public static final DeferredItem<BlockItem> CONCRETE_CYAN_SLAB = ITEMS.register("concrete_cyan_slab", () -> new BlockItem(ModBlocks.CONCRETE_CYAN_SLAB.get(), new Item.Properties()));
    public static final DeferredItem<BlockItem> CONCRETE_PURPLE_STAIRS = ITEMS.register("concrete_purple_stairs", () -> new BlockItem(ModBlocks.CONCRETE_PURPLE_STAIRS.get(), new Item.Properties()));
    public static final DeferredItem<BlockItem> CONCRETE_PURPLE_SLAB = ITEMS.register("concrete_purple_slab", () -> new BlockItem(ModBlocks.CONCRETE_PURPLE_SLAB.get(), new Item.Properties()));
    public static final DeferredItem<BlockItem> CONCRETE_BLUE_STAIRS = ITEMS.register("concrete_blue_stairs", () -> new BlockItem(ModBlocks.CONCRETE_BLUE_STAIRS.get(), new Item.Properties()));
    public static final DeferredItem<BlockItem> CONCRETE_BLUE_SLAB = ITEMS.register("concrete_blue_slab", () -> new BlockItem(ModBlocks.CONCRETE_BLUE_SLAB.get(), new Item.Properties()));
    public static final DeferredItem<BlockItem> CONCRETE_BROWN_STAIRS = ITEMS.register("concrete_brown_stairs", () -> new BlockItem(ModBlocks.CONCRETE_BROWN_STAIRS.get(), new Item.Properties()));
    public static final DeferredItem<BlockItem> CONCRETE_BROWN_SLAB = ITEMS.register("concrete_brown_slab", () -> new BlockItem(ModBlocks.CONCRETE_BROWN_SLAB.get(), new Item.Properties()));
    public static final DeferredItem<BlockItem> CONCRETE_GREEN_STAIRS = ITEMS.register("concrete_green_stairs", () -> new BlockItem(ModBlocks.CONCRETE_GREEN_STAIRS.get(), new Item.Properties()));
    public static final DeferredItem<BlockItem> CONCRETE_GREEN_SLAB = ITEMS.register("concrete_green_slab", () -> new BlockItem(ModBlocks.CONCRETE_GREEN_SLAB.get(), new Item.Properties()));
    public static final DeferredItem<BlockItem> CONCRETE_RED_STAIRS = ITEMS.register("concrete_red_stairs", () -> new BlockItem(ModBlocks.CONCRETE_RED_STAIRS.get(), new Item.Properties()));
    public static final DeferredItem<BlockItem> CONCRETE_RED_SLAB = ITEMS.register("concrete_red_slab", () -> new BlockItem(ModBlocks.CONCRETE_RED_SLAB.get(), new Item.Properties()));
    public static final DeferredItem<BlockItem> CONCRETE_BLACK_STAIRS = ITEMS.register("concrete_black_stairs", () -> new BlockItem(ModBlocks.CONCRETE_BLACK_STAIRS.get(), new Item.Properties()));
    public static final DeferredItem<BlockItem> CONCRETE_BLACK_SLAB = ITEMS.register("concrete_black_slab", () -> new BlockItem(ModBlocks.CONCRETE_BLACK_SLAB.get(), new Item.Properties()));
    public static final DeferredItem<BlockItem> CONCRETE_REBAR_STAIRS = ITEMS.register("concrete_rebar_stairs", () -> new BlockItem(ModBlocks.CONCRETE_REBAR_STAIRS.get(), new Item.Properties()));
    public static final DeferredItem<BlockItem> CONCRETE_REBAR_SLAB = ITEMS.register("concrete_rebar_slab", () -> new BlockItem(ModBlocks.CONCRETE_REBAR_SLAB.get(), new Item.Properties()));
    public static final DeferredItem<BlockItem> CONCRETE_ASBESTOS_STAIRS = ITEMS.register("concrete_asbestos_stairs", () -> new BlockItem(ModBlocks.CONCRETE_ASBESTOS_STAIRS.get(), new Item.Properties()));
    public static final DeferredItem<BlockItem> CONCRETE_ASBESTOS_SLAB = ITEMS.register("concrete_asbestos_slab", () -> new BlockItem(ModBlocks.CONCRETE_ASBESTOS_SLAB.get(), new Item.Properties()));
    public static final DeferredItem<BlockItem> CONCRETE_SUPER_STAIRS = ITEMS.register("concrete_super_stairs", () -> new BlockItem(ModBlocks.CONCRETE_SUPER_STAIRS.get(), new Item.Properties()));
    public static final DeferredItem<BlockItem> CONCRETE_SUPER_SLAB = ITEMS.register("concrete_super_slab", () -> new BlockItem(ModBlocks.CONCRETE_SUPER_SLAB.get(), new Item.Properties()));
    public static final DeferredItem<BlockItem> CONCRETE_TILE_STAIRS = ITEMS.register("concrete_tile_stairs", () -> new BlockItem(ModBlocks.CONCRETE_TILE_STAIRS.get(), new Item.Properties()));
    public static final DeferredItem<BlockItem> CONCRETE_TILE_SLAB = ITEMS.register("concrete_tile_slab", () -> new BlockItem(ModBlocks.CONCRETE_TILE_SLAB.get(), new Item.Properties()));
    public static final DeferredItem<BlockItem> BRICK_CONCRETE_STAIRS = ITEMS.register("brick_concrete_stairs", () -> new BlockItem(ModBlocks.BRICK_CONCRETE_STAIRS.get(), new Item.Properties()));
    public static final DeferredItem<BlockItem> BRICK_CONCRETE_SLAB = ITEMS.register("brick_concrete_slab", () -> new BlockItem(ModBlocks.BRICK_CONCRETE_SLAB.get(), new Item.Properties()));
    public static final DeferredItem<BlockItem> BRICK_CONCRETE_CRACKED_STAIRS = ITEMS.register("brick_concrete_cracked_stairs", () -> new BlockItem(ModBlocks.BRICK_CONCRETE_CRACKED_STAIRS.get(), new Item.Properties()));
    public static final DeferredItem<BlockItem> BRICK_CONCRETE_CRACKED_SLAB = ITEMS.register("brick_concrete_cracked_slab", () -> new BlockItem(ModBlocks.BRICK_CONCRETE_CRACKED_SLAB.get(), new Item.Properties()));
    public static final DeferredItem<BlockItem> BRICK_CONCRETE_MOSSY_STAIRS = ITEMS.register("brick_concrete_mossy_stairs", () -> new BlockItem(ModBlocks.BRICK_CONCRETE_MOSSY_STAIRS.get(), new Item.Properties()));
    public static final DeferredItem<BlockItem> BRICK_CONCRETE_MOSSY_SLAB = ITEMS.register("brick_concrete_mossy_slab", () -> new BlockItem(ModBlocks.BRICK_CONCRETE_MOSSY_SLAB.get(), new Item.Properties()));
    public static final DeferredItem<BlockItem> BRICK_CONCRETE_BROKEN_STAIRS = ITEMS.register("brick_concrete_broken_stairs", () -> new BlockItem(ModBlocks.BRICK_CONCRETE_BROKEN_STAIRS.get(), new Item.Properties()));
    public static final DeferredItem<BlockItem> BRICK_CONCRETE_BROKEN_SLAB = ITEMS.register("brick_concrete_broken_slab", () -> new BlockItem(ModBlocks.BRICK_CONCRETE_BROKEN_SLAB.get(), new Item.Properties()));
    public static final DeferredItem<BlockItem> BRICK_CONCRETE_MARKED_STAIRS = ITEMS.register("brick_concrete_marked_stairs", () -> new BlockItem(ModBlocks.BRICK_CONCRETE_MARKED_STAIRS.get(), new Item.Properties()));
    public static final DeferredItem<BlockItem> BRICK_CONCRETE_MARKED_SLAB = ITEMS.register("brick_concrete_marked_slab", () -> new BlockItem(ModBlocks.BRICK_CONCRETE_MARKED_SLAB.get(), new Item.Properties()));
    public static final DeferredItem<BlockItem> CONCRETE_COLORED_EXT_HAZARD_STAIRS = ITEMS.register("concrete_colored_ext_hazard_stairs", () -> new BlockItem(ModBlocks.CONCRETE_COLORED_EXT_HAZARD_STAIRS.get(), new Item.Properties()));
    public static final DeferredItem<BlockItem> CONCRETE_COLORED_EXT_HAZARD_SLAB = ITEMS.register("concrete_colored_ext_hazard_slab", () -> new BlockItem(ModBlocks.CONCRETE_COLORED_EXT_HAZARD_SLAB.get(), new Item.Properties()));

    private static DeferredItem<Item> simple(String name) { return ITEMS.registerSimpleItem(name, new Item.Properties()); }
    private static DeferredItem<RadioactiveItem> radioactive(String name, float rad) { return ITEMS.register(name, () -> new RadioactiveItem(new Item.Properties(), rad)); }
    private static DeferredItem<ItemStamp> stamp(String name, int durability, ItemStamp.StampType type) { return ITEMS.register(name, () -> new ItemStamp(new Item.Properties().durability(durability), type)); }
    private static DeferredItem<ItemMachineUpgrade> upgrade(String name, ItemMachineUpgrade.UpgradeType type, int level) { return ITEMS.register(name, () -> new ItemMachineUpgrade(new Item.Properties().stacksTo(1), type, level)); }
    private static DeferredItem<ItemSolderingFluidCell> fluidCell(String name, ItemSolderingFluidCell.FluidType type) { return ITEMS.register(name, () -> new ItemSolderingFluidCell(new Item.Properties().stacksTo(1), type)); }

    private ModItems() {}
    public static void register(IEventBus modEventBus) { ITEMS.register(modEventBus); }
}
